export const movieGenres = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "Horror",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "Western",
];
export const movieData = [
  {
    title: "Inception",
    description:
      "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into the mind of a CEO.",
    director: "Christopher Nolan",
    duration: 148,
    releaseDate: new Date("2010-07-16"),
    posterUrl: "https://example.com/inception_poster.jpg",
    trailerUrl: "https://example.com/inception_trailer.mp4",
    cast: [
      "Leonardo DiCaprio",
      "Joseph Gordon-Levitt",
      "Elliot Page",
      "Tom Hardy",
      "Ken Watanabe",
      "Marion Cotillard",
    ],
    genreNames: ["Action", "Sci-Fi", "Thriller"],
    rated: "PG-13",
  },
  {
    title: "The Shawshank Redemption",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    director: "Frank Darabont",
    duration: 142,
    releaseDate: new Date("1994-09-23"),
    posterUrl: "https://example.com/shawshank_poster.jpg",
    trailerUrl: "https://example.com/shawshank_trailer.mp4",
    cast: [
      "Tim Robbins",
      "Morgan Freeman",
      "Bob Gunton",
      "William Sadler",
      "Clancy Brown",
      "Gil Bellows",
    ],
    genreNames: ["Drama"],
    rated: "R",
  },
  {
    title: "The Godfather",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    director: "Francis Ford Coppola",
    duration: 175,
    releaseDate: new Date("1972-03-24"),
    posterUrl: "https://example.com/godfather_poster.jpg",
    trailerUrl: "https://example.com/godfather_trailer.mp4",
    cast: [
      "Marlon Brando",
      "Al Pacino",
      "James Caan",
      "Robert Duvall",
      "Diane Keaton",
      "Talia Shire",
    ],
    genreNames: ["Crime", "Drama"],
    rated: "R",
  },
  {
    title: "Pulp Fiction",
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    director: "Quentin Tarantino",
    duration: 154,
    releaseDate: new Date("1994-10-14"),
    posterUrl: "https://example.com/pulpfiction_poster.jpg",
    trailerUrl: "https://example.com/pulpfiction_trailer.mp4",
    cast: [
      "John Travolta",
      "Samuel L. Jackson",
      "Uma Thurman",
      "Bruce Willis",
      "Ving Rhames",
      "Tim Roth",
    ],
    genreNames: ["Crime", "Drama"],
    rated: "R",
  },
  {
    title: "Forrest Gump",
    description:
      "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    director: "Robert Zemeckis",
    duration: 142,
    releaseDate: new Date("1994-07-06"),
    posterUrl: "https://example.com/forrestgump_poster.jpg",
    trailerUrl: "https://example.com/forrestgump_trailer.mp4",
    cast: [
      "Tom Hanks",
      "Robin Wright",
      "Gary Sinise",
      "Sally Field",
      "Mykelti Williamson",
      "Rebecca Williams",
    ],
    genreNames: ["Drama", "Romance"],
    rated: "PG-13",
  },
  {
    title: "The Dark Knight",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    director: "Christopher Nolan",
    duration: 152,
    releaseDate: new Date("2008-07-18"),
    posterUrl: "https://example.com/darkknight_poster.jpg",
    trailerUrl: "https://example.com/darkknight_trailer.mp4",
    cast: [
      "Christian Bale",
      "Heath Ledger",
      "Aaron Eckhart",
      "Michael Caine",
      "Gary Oldman",
      "Morgan Freeman",
    ],
    genreNames: ["Action", "Crime", "Drama"],
    rated: "PG-13",
  },
];

export const cinemaData = [
  {
    name: "Cineworld Downtown",
    owner: "John Smith",
    address: "123 Main Street, Downtown, NY 10001",
    phoneNumber: "+1234567890",
    imageUrl: "https://example.com/cineworld_downtown.jpg",
  },
  {
    name: "Starlight Cinema",
    owner: "Emma Johnson",
    address: "456 Broadway, West End, NY 10002",
    phoneNumber: "+1234567891",
    imageUrl: "https://example.com/starlight.jpg",
  },
  {
    name: "Landmark Theaters",
    owner: "David Williams",
    address: "789 Oak Avenue, East Side, NY 10003",
    phoneNumber: "+1234567892",
    imageUrl: "https://example.com/landmark.jpg",
  },
  {
    name: "Regal Cinemas",
    owner: "Sarah Brown",
    address: "101 Pine Street, North Side, NY 10004",
    phoneNumber: "+1234567893",
    imageUrl: "https://example.com/regal.jpg",
  },
  {
    name: "AMC Theaters",
    owner: "Michael Davis",
    address: "202 Maple Road, South Side, NY 10005",
    phoneNumber: "+1234567894",
    imageUrl: "https://example.com/amc.jpg",
  },
];
